version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo No build step needed
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Skipping tests (none defined)

artifacts:
  files:
    - '**/*'
  discard-paths: no
